const characters = {
    anime: [
        { id: "goku", name: "Goku", anime: "Dragon Ball", image: "/images/goku.jpg" },
        { id: "naruto", name: "Naruto Uzumaki", anime: "Naruto", image: "/images/naruto.jpg" },
        { id: "luffy", name: "Monkey D. Luffy", anime: "One Piece", image: "/images/luffy.jpg" },
        { id: "gojo", name: "Satoru Gojo", anime: "Jujutsu Kaisen", image: "/images/gojo.jpg" },
        { id: "tanjiro", name: "Tanjiro Kamado", anime: "Demon Slayer", image: "/images/tanjiro.jpg" },
        { id: "nezuko", name: "Nezuko Kamado", anime: "Demon Slayer", image: "/images/nezuko.jpg" },
        { id: "zoro", name: "Roronoa Zoro", anime: "One Piece", image: "/images/zoro.jpg" },
        { id: "eren", name: "Eren Yeager", anime: "Attack on Titan", image: "/images/eren.jpg" },
        { id: "saitama", name: "Saitama", anime: "One Punch Man", image: "/images/saitama.jpg" },
        { id: "mikasa", name: "Mikasa Ackerman", anime: "Attack on Titan", image: "/images/mikasa.jpg" },
        { id: "ichigo", name: "Ichigo Kurosaki", anime: "Bleach", image: "/images/ichigo.jpg" },
        { id: "light", name: "Light Yagami", anime: "Death Note", image: "/images/light.jpg" },
        { id: "levi", name: "Levi Ackerman", anime: "Attack on Titan", image: "/images/levi.jpg" },
        { id: "killua", name: "Killua Zoldyck", anime: "Hunter x Hunter", image: "/images/killua.jpg" },
        { id: "gon", name: "Gon Freecss", anime: "Hunter x Hunter", image: "/images/gon.jpg" },
        { id: "denji", name: "Denji", anime: "Chainsaw Man", image: "/images/denji.jpg" },
        { id: "power", name: "Power", anime: "Chainsaw Man", image: "/images/power.jpg" },
        { id: "deku", name: "Izuku Midoriya", anime: "My Hero Academia", image: "/images/deku.jpg" },
        { id: "bakugo", name: "Katsuki Bakugo", anime: "My Hero Academia", image: "/images/bakugo.jpg" },
        { id: "aizen", name: "Sosuke Aizen", anime: "Bleach", image: "/images/aizen.jpg" },
        { id: "itachi", name: "Itachi Uchiha", anime: "Naruto", image: "/images/itachi.jpg" },
        { id: "vegeta", name: "Vegeta", anime: "Dragon Ball", image: "/images/vegeta.jpg" },
        { id: "rem", name: "Rem", anime: "Re:Zero", image: "/images/rem.jpg" },
        { id: "asuna", name: "Asuna Yuuki", anime: "Sword Art Online", image: "/images/asuna.jpg" }
    ],
    gaming: [
        { id: "mario", name: "Mario", anime: "Super Mario", image: "/images/mario.jpg" },
        { id: "sonic", name: "Sonic", anime: "Sonic the Hedgehog", image: "/images/sonic.jpg" },
        { id: "pikachu", name: "Pikachu", anime: "Pokémon", image: "/images/pikachu.jpg" },
        { id: "kratos", name: "Kratos", anime: "God of War", image: "/images/kratos.jpg" },
        { id: "masterchief", name: "Master Chief", anime: "Halo", image: "/images/masterchief.jpg" },
        { id: "cloud", name: "Cloud Strife", anime: "Final Fantasy", image: "/images/cloud.jpg" },
        { id: "link", name: "Link", anime: "The Legend of Zelda", image: "/images/link.jpg" },
        { id: "samus", name: "Samus Aran", anime: "Metroid", image: "/images/samus.jpg" },
        { id: "doomslayer", name: "Doom Slayer", anime: "DOOM", image: "/images/doomslayer.jpg" },
        { id: "arthur", name: "Arthur Morgan", anime: "Red Dead Redemption", image: "/images/arthur.jpg" },
        { id: "geralt", name: "Geralt of Rivia", anime: "The Witcher", image: "/images/geralt.jpg" },
        { id: "ellie", name: "Ellie", anime: "The Last of Us", image: "/images/ellie.jpg" },
        { id: "aloy", name: "Aloy", anime: "Horizon Zero Dawn", image: "/images/aloy.jpg" }
    ],
    movies: [
        { id: "ironman", name: "Iron Man", anime: "Marvel", image: "/images/ironman.jpg" },
        { id: "spiderman", name: "Spider-Man", anime: "Marvel", image: "/images/spiderman.jpg" },
        { id: "thor", name: "Thor", anime: "Marvel", image: "/images/thor.jpg" },
        { id: "blackpanther", name: "Black Panther", anime: "Marvel", image: "/images/blackpanther.jpg" },
        { id: "batman", name: "Batman", anime: "DC", image: "/images/batman.jpg" },
        { id: "superman", name: "Superman", anime: "DC", image: "/images/superman.jpg" },
        { id: "wonderwoman", name: "Wonder Woman", anime: "DC", image: "/images/wonderwoman.jpg" },
        { id: "harrypotter", name: "Harry Potter", anime: "Harry Potter", image: "/images/harrypotter.jpg" },
        { id: "legolas", name: "Legolas", anime: "Lord of the Rings", image: "/images/legolas.jpg" },
        { id: "aragorn", name: "Aragorn", anime: "Lord of the Rings", image: "/images/aragorn.jpg" },
        { id: "johnwick", name: "John Wick", anime: "John Wick", image: "/images/johnwick.jpg" },
        { id: "jacksparrow", name: "Jack Sparrow", anime: "Pirates of the Caribbean", image: "/images/jacksparrow.jpg" },
        { id: "dominictoretto", name: "Dominic Toretto", anime: "Fast & Furious", image: "/images/dominictoretto.jpg" },
        { id: "bond", name: "James Bond", anime: "007", image: "/images/bond.jpg" },
        { id: "indianajones", name: "Indiana Jones", anime: "Indiana Jones", image: "/images/indianajones.jpg" }
    ],
    tvshows: [
        { id: "walterwhite", name: "Walter White", anime: "Breaking Bad", image: "/images/walterwhite.jpg" },
        { id: "jessepinkman", name: "Jesse Pinkman", anime: "Breaking Bad", image: "/images/jessepinkman.jpg" },
        { id: "tonysoprano", name: "Tony Soprano", anime: "The Sopranos", image: "/images/tonysoprano.jpg" },
        { id: "don draper", name: "Don Draper", anime: "Mad Men", image: "/images/dondraper.jpg" },
        { id: "rickgrimes", name: "Rick Grimes", anime: "The Walking Dead", image: "/images/rickgrimes.jpg" },
        { id: "daryldixon", name: "Daryl Dixon", anime: "The Walking Dead", image: "/images/daryldixon.jpg" },
        { id: "drogon", name: "Daenerys Targaryen", anime: "Game of Thrones", image: "/images/drogon.jpg" },
        { id: "jonsnow", name: "Jon Snow", anime: "Game of Thrones", image: "/images/jonsnow.jpg" },
        { id: "tyrion", name: "Tyrion Lannister", anime: "Game of Thrones", image: "/images/tyrion.jpg" },
        { id: "sheldon", name: "Sheldon Cooper", anime: "The Big Bang Theory", image: "/images/sheldon.jpg" },
        { id: "frankunderwood", name: "Frank Underwood", anime: "House of Cards", image: "/images/frankunderwood.jpg" },
        { id: "michael scott", name: "Michael Scott", anime: "The Office", image: "/images/michaelscott.jpg" },
        { id: "pabloescobar", name: "Pablo Escobar", anime: "Narcos", image: "/images/pabloescobar.jpg" },
        { id: "sherlock", name: "Sherlock Holmes", anime: "Sherlock", image: "/images/sherlock.jpg" }
    ],
    music: [
        { id: "taylor", name: "Taylor Swift", anime: "Pop", image: "/images/taylor.jpg" },
        { id: "beyonce", name: "Beyoncé", anime: "R&B", image: "/images/beyonce.jpg" },
        { id: "ed sheeran", name: "Ed Sheeran", anime: "Pop", image: "/images/edsheeran.jpg" },
        { id: "adele", name: "Adele", anime: "Pop", image: "/images/adele.jpg" },
        { id: "drake", name: "Drake", anime: "Hip Hop", image: "/images/drake.jpg" },
        { id: "eminem", name: "Eminem", anime: "Hip Hop", image: "/images/eminem.jpg" },
        { id: "kendrick", name: "Kendrick Lamar", anime: "Hip Hop", image: "/images/kendrick.jpg" },
        { id: "ariana", name: "Ariana Grande", anime: "Pop", image: "/images/ariana.jpg" },
        { id: "justinbieber", name: "Justin Bieber", anime: "Pop", image: "/images/justinbieber.jpg" },
        { id: "badbunny", name: "Bad Bunny", anime: "Reggaeton", image: "/images/badbunny.jpg" },
        { id: "harrystyles", name: "Harry Styles", anime: "Pop", image: "/images/harrystyles.jpg" },
        { id: "billieeilish", name: "Billie Eilish", anime: "Alternative", image: "/images/billieeilish.jpg" },
        { id: "postmalone", name: "Post Malone", anime: "Hip Hop", image: "/images/postmalone.jpg" },
        { id: "dualipa", name: "Dua Lipa", anime: "Pop", image: "/images/dualipa.jpg" }
    ],
    sports: [
        { id: "messi", name: "Lionel Messi", anime: "Football", image: "/images/messi.jpg" },
        { id: "ronaldo", name: "Cristiano Ronaldo", anime: "Football", image: "/images/ronaldo.jpg" },
        { id: "lebron", name: "LeBron James", anime: "Basketball", image: "/images/lebron.jpg" },
        { id: "jordan", name: "Michael Jordan", anime: "Basketball", image: "/images/jordan.jpg" },
        { id: "kobe", name: "Kobe Bryant", anime: "Basketball", image: "/images/kobe.jpg" },
        { id: "serena", name: "Serena Williams", anime: "Tennis", image: "/images/serena.jpg" },
        { id: "federer", name: "Roger Federer", anime: "Tennis", image: "/images/federer.jpg" },
        { id: "tigerwoods", name: "Tiger Woods", anime: "Golf", image: "/images/tigerwoods.jpg" },
        { id: "usainbolt", name: "Usain Bolt", anime: "Athletics", image: "/images/usainbolt.jpg" },
        { id: "tom brady", name: "Tom Brady", anime: "American Football", image: "/images/tombrady.jpg" },
        { id: "msd", name: "Mahendra Singh Dhoni", anime: "Indian Cricketer", image: "/images/mahi.jpg" },
        { id: "neymar", name: "Neymar Jr", anime: "Football", image: "/images/neymar.jpg" },
        { id: "mbappe", name: "Kylian Mbappé", anime: "Football", image: "/images/mbappe.jpg" },
        { id: "haaland", name: "Erling Haaland", anime: "Football", image: "/images/haaland.jpg" }
    ],
    superheroes: [
        { id: "spiderman", name: "Spider-Man", anime: "Marvel", image: "/images/spiderman2.jpg" },
        { id: "ironman", name: "Iron Man", anime: "Marvel", image: "/images/ironman2.jpg" },
        { id: "captainamerica", name: "Captain America", anime: "Marvel", image: "/images/captainamerica.jpg" },
        { id: "thor", name: "Thor", anime: "Marvel", image: "/images/thor2.jpg" },
        { id: "blackpanther", name: "Black Panther", anime: "Marvel", image: "/images/blackpanther2.jpg" },
        { id: "batman", name: "Batman", anime: "DC", image: "/images/batman2.jpg" },
        { id: "superman", name: "Superman", anime: "DC", image: "/images/superman2.jpg" },
        { id: "wonderwoman", name: "Wonder Woman", anime: "DC", image: "/images/wonderwoman2.jpg" },
        { id: "flash", name: "The Flash", anime: "DC", image: "/images/flash.jpg" },
        { id: "aquaman", name: "Aquaman", anime: "DC", image: "/images/aquaman.jpg" },
        { id: "deadpool", name: "Deadpool", anime: "Marvel", image: "/images/deadpool.jpg" },
        { id: "wolverine", name: "Wolverine", anime: "Marvel", image: "/images/wolverine.jpg" },
        { id: "doctorstrange", name: "Doctor Strange", anime: "Marvel", image: "/images/doctorstrange.jpg" },
        { id: "antman", name: "Ant-Man", anime: "Marvel", image: "/images/antman.jpg" }
    ],
    videogames: [
        { id: "mario", name: "Mario", anime: "Super Mario", image: "/images/mario2.jpg" },
        { id: "sonic", name: "Sonic", anime: "Sonic the Hedgehog", image: "/images/sonic2.jpg" },
        { id: "pikachu", name: "Pikachu", anime: "Pokémon", image: "/images/pikachu2.jpg" },
        { id: "kratos", name: "Kratos", anime: "God of War", image: "/images/kratos2.jpg" },
        { id: "masterchief", name: "Master Chief", anime: "Halo", image: "/images/masterchief2.jpg" },
        { id: "cloud", name: "Cloud Strife", anime: "Final Fantasy", image: "/images/cloud2.jpg" },
        { id: "link", name: "Link", anime: "The Legend of Zelda", image: "/images/link2.jpg" },
        { id: "samus", name: "Samus Aran", anime: "Metroid", image: "/images/samus2.jpg" },
        { id: "doomslayer", name: "Doom Slayer", anime: "DOOM", image: "/images/doomslayer2.jpg" },
        { id: "arthur", name: "Arthur Morgan", anime: "Red Dead Redemption", image: "/images/arthur2.jpg" },
        { id: "geralt", name: "Geralt of Rivia", anime: "The Witcher", image: "/images/geralt2.jpg" },
        { id: "ellie", name: "Ellie", anime: "The Last of Us", image: "/images/ellie2.jpg" },
        { id: "aloy", name: "Aloy", anime: "Horizon Zero Dawn", image: "/images/aloy2.jpg" },
        { id: "sephiroth", name: "Sephiroth", anime: "Final Fantasy", image: "/images/sephiroth.jpg" }
    ],
    books: [
        { id: "harrypotter", name: "Harry Potter", anime: "Harry Potter", image: "/images/harrypotter2.jpg" },
        { id: "hermione", name: "Hermione Granger", anime: "Harry Potter", image: "/images/hermione.jpg" },
        { id: "ronweasley", name: "Ron Weasley", anime: "Harry Potter", image: "/images/ronweasley.jpg" },
        { id: "frodo", name: "Frodo Baggins", anime: "Lord of the Rings", image: "/images/frodo.jpg" },
        { id: "gandalf", name: "Gandalf", anime: "Lord of the Rings", image: "/images/gandalf.jpg" },
        { id: "katniss", name: "Katniss Everdeen", anime: "The Hunger Games", image: "/images/katniss.jpg" },
        { id: "peeta", name: "Peeta Mellark", anime: "The Hunger Games", image: "/images/peeta.jpg" },
        { id: "sherlock", name: "Sherlock Holmes", anime: "Sherlock Holmes", image: "/images/sherlock2.jpg" },
        { id: "dumbledore", name: "Albus Dumbledore", anime: "Harry Potter", image: "/images/dumbledore.jpg" },
        { id: "voldemort", name: "Lord Voldemort", anime: "Harry Potter", image: "/images/voldemort.jpg" },
        { id: "bilbo", name: "Bilbo Baggins", anime: "The Hobbit", image: "/images/bilbo.jpg" },
        { id: "thorinoakenshield", name: "Thorin Oakenshield", anime: "The Hobbit", image: "/images/thorinoakenshield.jpg" },
        { id: "gatsby", name: "Jay Gatsby", anime: "The Great Gatsby", image: "/images/gatsby.jpg" },
        
    ],
    kpop: [
        { id: "jimin", name: "Jimin", anime: "BTS", image: "/images/jimin.jpg" },
        { id: "jungkook", name: "Jungkook", anime: "BTS", image: "/images/jungkook.jpg" },
        { id: "v", name: "V", anime: "BTS", image: "/images/v.jpg" },
        { id: "rm", name: "RM", anime: "BTS", image: "/images/rm.jpg" },
        { id: "jhope", name: "J-Hope", anime: "BTS", image: "/images/jhope.jpg" },
        { id: "suga", name: "Suga", anime: "BTS", image: "/images/suga.jpg" },
        { id: "jin", name: "Jin", anime: "BTS", image: "/images/jin.jpg" },
        { id: "lisa", name: "Lisa", anime: "BLACKPINK", image: "/images/lisa.jpg" },
        { id: "jennie", name: "Jennie", anime: "BLACKPINK", image: "/images/jennie.jpg" },
        { id: "rose", name: "Rosé", anime: "BLACKPINK", image: "/images/rose.jpg" },
        { id: "jisoo", name: "Jisoo", anime: "BLACKPINK", image: "/images/jisoo.jpg" },
        { id: "chungha", name: "Chungha", anime: "Soloist", image: "/images/chungha.jpg" },
        { id: "taemin", name: "Taemin", anime: "SHINee", image: "/images/taemin.jpg" },
        { id: "iu", name: "IU", anime: "Soloist", image: "/images/iu.jpg" }
    ]
};

const categoryEmojis = {
    anime: '🎌',
    gaming: '🎮',
    movies: '🎬',
    tvshows: '📺',
    music: '🎵',
    sports: '🏆',
    superheroes: '🦸',
    videogames: '👾',
    books: '📚',
    kpop: '🎤'
};

const categoryNames = {
    anime: 'Anime',
    gaming: 'Gaming',
    movies: 'Movies',
    tvshows: 'TV Shows',
    music: 'Music',
    sports: 'Sports',
    superheroes: 'Superheroes',
    videogames: 'Video Games',
    books: 'Books',
    kpop: 'K-Pop'
};

module.exports = { characters, categoryEmojis, categoryNames };